Add files via upload
(Python 3.6.4)
returns error:
 
when File "mirrorscript.py", line 11
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

Solution: 
Updated python versions now use print("") instead of print ""
-all print methods used in mirrorscript.py are now converted to new required format